---
- name: Configure time synchronization and timezone
  become: true
  notify: Restart chrony service
  block:
    - name: Configure chrony time synchronization
      ansible.builtin.template:
        src: "chrony.conf.j2"
        dest: "{{ pve_config_time_sync_conf_path }}"
        mode: "0644"
      register: pve_config_time_sync_chrony_config

    - name: Set timezone and hardware clock
      community.general.timezone:
        name: "{{ pve_config_time_sync_timezone }}"
        hwclock: "{{ pve_config_time_sync_hwclock | default(omit) }}"
      register: pve_config_time_sync_tz_config
...
