# SPDX-License-Identifier: MIT-0
---
# handlers file for pve_config

- name: Pause for 15 seconds
  ansible.builtin.pause:
    seconds: 15

- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: 600   # seconds to wait for the host to come back
    msg: "Reboot initiated by Ansible"
    pre_reboot_delay: 5   # seconds before reboot starts
    post_reboot_delay: 15 # seconds after host is up before marking task complete
    connect_timeout: 5    # SSH connection timeout

- name: Restart chrony service
  ansible.builtin.service:
    name: "chronyd"
    state: restarted
  become: true
...
